[2025-01-14T10:41:07.859+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prepare_churn_dataset.load manual__2025-01-14T10:41:01.588616+00:00 [queued]>
[2025-01-14T10:41:07.866+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prepare_churn_dataset.load manual__2025-01-14T10:41:01.588616+00:00 [queued]>
[2025-01-14T10:41:07.867+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-14T10:41:07.884+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2025-01-14 10:41:01.588616+00:00
[2025-01-14T10:41:07.892+0000] {standard_task_runner.py:57} INFO - Started process 675 to run task
[2025-01-14T10:41:07.894+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'prepare_churn_dataset', 'load', 'manual__2025-01-14T10:41:01.588616+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/churn.py', '--cfg-path', '/tmp/tmp09g7v58j']
[2025-01-14T10:41:07.896+0000] {standard_task_runner.py:85} INFO - Job 189: Subtask load
[2025-01-14T10:41:07.941+0000] {task_command.py:416} INFO - Running <TaskInstance: prepare_churn_dataset.load manual__2025-01-14T10:41:01.588616+00:00 [running]> on host 912df0823751
[2025-01-14T10:41:08.091+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prepare_churn_dataset' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T10:41:01.588616+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-14T10:41:01.588616+00:00'
[2025-01-14T10:41:08.093+0000] {churn.py:103} INFO - Загрузка данных в целевую таблицу.
[2025-01-14T10:41:08.101+0000] {base.py:73} INFO - Using connection ID 'destination_db' for task execution.
[2025-01-14T10:41:35.517+0000] {sql.py:512} INFO - Loaded 1000 rows into users_churn so far
[2025-01-14T10:42:03.347+0000] {sql.py:512} INFO - Loaded 2000 rows into users_churn so far
[2025-01-14T10:42:31.642+0000] {sql.py:512} INFO - Loaded 3000 rows into users_churn so far
[2025-01-14T10:42:59.279+0000] {sql.py:512} INFO - Loaded 4000 rows into users_churn so far
[2025-01-14T10:43:27.059+0000] {sql.py:512} INFO - Loaded 5000 rows into users_churn so far
[2025-01-14T10:43:54.505+0000] {sql.py:512} INFO - Loaded 6000 rows into users_churn so far
[2025-01-14T10:44:21.977+0000] {sql.py:512} INFO - Loaded 7000 rows into users_churn so far
[2025-01-14T10:44:23.235+0000] {sql.py:515} INFO - Done loading. Loaded a total of 7043 rows into users_churn
[2025-01-14T10:44:23.237+0000] {churn.py:112} INFO - Данные успешно загружены.
[2025-01-14T10:44:23.238+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-01-14T10:44:23.250+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_churn_dataset, task_id=load, execution_date=20250114T104101, start_date=20250114T104107, end_date=20250114T104423
[2025-01-14T10:44:23.285+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-14T10:44:23.302+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
