[2025-01-13T20:38:23.631+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: users_churn_dag.create_table manual__2025-01-13T20:38:17.349557+00:00 [queued]>
[2025-01-13T20:38:23.637+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: users_churn_dag.create_table manual__2025-01-13T20:38:17.349557+00:00 [queued]>
[2025-01-13T20:38:23.638+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-01-13T20:38:23.649+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): create_table> on 2025-01-13 20:38:17.349557+00:00
[2025-01-13T20:38:23.656+0000] {standard_task_runner.py:57} INFO - Started process 76 to run task
[2025-01-13T20:38:23.659+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'users_churn_dag', 'create_table', 'manual__2025-01-13T20:38:17.349557+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/churn.py', '--cfg-path', '/tmp/tmpvgc71our']
[2025-01-13T20:38:23.660+0000] {standard_task_runner.py:85} INFO - Job 134: Subtask create_table
[2025-01-13T20:38:23.699+0000] {task_command.py:416} INFO - Running <TaskInstance: users_churn_dag.create_table manual__2025-01-13T20:38:17.349557+00:00 [running]> on host fd0de9b165bb
[2025-01-13T20:38:23.761+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='users_churn_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T20:38:17.349557+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-13T20:38:17.349557+00:00'
[2025-01-13T20:38:23.764+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-01-13T20:38:23.765+0000] {base.py:73} INFO - Using connection ID 'destination_db' for task execution.
[2025-01-13T20:38:24.226+0000] {logging_mixin.py:154} INFO - Таблица users_churn уже существует.
[2025-01-13T20:38:24.252+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-01-13T20:38:24.261+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=users_churn_dag, task_id=create_table, execution_date=20250113T203817, start_date=20250113T203823, end_date=20250113T203824
[2025-01-13T20:38:24.313+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-13T20:38:24.335+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
