[2025-01-30T06:11:12.365+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T06:11:12.381+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prepare_churn_dataset.extract manual__2025-01-30T06:11:09.552302+00:00 [queued]>
[2025-01-30T06:11:12.388+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prepare_churn_dataset.extract manual__2025-01-30T06:11:09.552302+00:00 [queued]>
[2025-01-30T06:11:12.389+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T06:11:12.401+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2025-01-30 06:11:09.552302+00:00
[2025-01-30T06:11:12.410+0000] {standard_task_runner.py:72} INFO - Started process 158 to run task
[2025-01-30T06:11:12.417+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prepare_churn_dataset', 'extract', 'manual__2025-01-30T06:11:09.552302+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/churn.py', '--cfg-path', '/tmp/tmptyahgu3i']
[2025-01-30T06:11:12.420+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask extract
[2025-01-30T06:11:12.498+0000] {task_command.py:467} INFO - Running <TaskInstance: prepare_churn_dataset.extract manual__2025-01-30T06:11:09.552302+00:00 [running]> on host 0be31ceb717f
[2025-01-30T06:11:12.594+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prepare_churn_dataset' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T06:11:09.552302+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T06:11:09.552302+00:00'
[2025-01-30T06:11:12.598+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T06:11:12.598+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T06:11:12.599+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2025-01-30 06:11:12.382749+00:00
[2025-01-30T06:11:12.599+0000] {logging_mixin.py:190} INFO - Dag name:prepare_churn_dataset and current dag run status:running
[2025-01-30T06:11:12.600+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T06:11:12.602+0000] {churn.py:71} INFO - Извлечение данных из источника.
[2025-01-30T06:11:12.611+0000] {base.py:84} INFO - Retrieving connection 'source_db'
[2025-01-30T06:11:12.612+0000] {sql.py:186} WARNING - This setter is for backward compatibility and should not be used.
Since the introduction of connection property, the providers listed below breaks due to assigning value to self.connection in their __init__ method.
* apache-***-providers-mysql<5.7.1
* apache-***-providers-elasticsearch<5.5.1
* apache-***-providers-postgres<5.13.0
[2025-01-30T06:11:12.754+0000] {warnings.py:109} WARNING - /opt/***/dags/churn.py:86: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(sql, conn)

[2025-01-30T06:11:13.718+0000] {churn.py:88} INFO - Данные успешно извлечены.
[2025-01-30T06:11:13.720+0000] {python.py:240} INFO - Done. Returned value was:      customer_id  begin_date  ... dependents multiple_lines
0     7590-VHVEG  2020-01-01  ...         No           None
1     5575-GNVDE  2017-04-01  ...         No             No
2     3668-QPYBK  2019-10-01  ...         No             No
3     7795-CFOCW  2016-05-01  ...         No           None
4     9237-HQITU  2019-09-01  ...         No             No
...          ...         ...  ...        ...            ...
7038  6840-RESVB  2018-02-01  ...        Yes            Yes
7039  2234-XADUH  2014-02-01  ...        Yes            Yes
7040  4801-JZAZL  2019-03-01  ...        Yes           None
7041  8361-LTMKD  2019-07-01  ...         No            Yes
7042  3186-AJIEK  2014-08-01  ...         No             No

[7043 rows x 20 columns]
[2025-01-30T06:11:13.837+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T06:11:13.838+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=prepare_churn_dataset, task_id=extract, run_id=manual__2025-01-30T06:11:09.552302+00:00, execution_date=20250130T061109, start_date=20250130T061112, end_date=20250130T061113
[2025-01-30T06:11:13.845+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T06:11:13.846+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T06:11:13.846+0000] {logging_mixin.py:190} INFO - Dag name:prepare_churn_dataset queued_at:2025-01-30 06:11:09.574344+00:00
[2025-01-30T06:11:13.847+0000] {logging_mixin.py:190} INFO - Task hostname:0be31ceb717f operator:_PythonDecoratedOperator
[2025-01-30T06:11:13.889+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T06:11:13.911+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-30T06:11:13.914+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
