[2025-01-18T08:08:22.482+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prepare_churn_dataset.load manual__2025-01-18T08:08:13.424501+00:00 [queued]>
[2025-01-18T08:08:22.492+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prepare_churn_dataset.load manual__2025-01-18T08:08:13.424501+00:00 [queued]>
[2025-01-18T08:08:22.492+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-18T08:08:22.506+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2025-01-18 08:08:13.424501+00:00
[2025-01-18T08:08:22.515+0000] {standard_task_runner.py:57} INFO - Started process 141 to run task
[2025-01-18T08:08:22.519+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'prepare_churn_dataset', 'load', 'manual__2025-01-18T08:08:13.424501+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/churn.py', '--cfg-path', '/tmp/tmpr730p0gk']
[2025-01-18T08:08:22.521+0000] {standard_task_runner.py:85} INFO - Job 213: Subtask load
[2025-01-18T08:08:22.570+0000] {task_command.py:416} INFO - Running <TaskInstance: prepare_churn_dataset.load manual__2025-01-18T08:08:13.424501+00:00 [running]> on host 5b7622f1d3e7
[2025-01-18T08:08:22.753+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prepare_churn_dataset' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-01-18T08:08:13.424501+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-18T08:08:13.424501+00:00'
[2025-01-18T08:08:22.755+0000] {churn.py:103} INFO - Загрузка данных в целевую таблицу.
[2025-01-18T08:08:22.764+0000] {base.py:73} INFO - Using connection ID 'destination_db' for task execution.
[2025-01-18T08:08:49.708+0000] {sql.py:512} INFO - Loaded 1000 rows into users_churn so far
[2025-01-18T08:09:16.432+0000] {sql.py:512} INFO - Loaded 2000 rows into users_churn so far
[2025-01-18T08:09:43.150+0000] {sql.py:512} INFO - Loaded 3000 rows into users_churn so far
[2025-01-18T08:10:10.115+0000] {sql.py:512} INFO - Loaded 4000 rows into users_churn so far
[2025-01-18T08:10:36.787+0000] {sql.py:512} INFO - Loaded 5000 rows into users_churn so far
[2025-01-18T08:11:03.384+0000] {sql.py:512} INFO - Loaded 6000 rows into users_churn so far
[2025-01-18T08:11:31.194+0000] {sql.py:512} INFO - Loaded 7000 rows into users_churn so far
[2025-01-18T08:11:32.461+0000] {sql.py:515} INFO - Done loading. Loaded a total of 7043 rows into users_churn
[2025-01-18T08:11:32.463+0000] {churn.py:112} INFO - Данные успешно загружены.
[2025-01-18T08:11:32.463+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-01-18T08:11:32.475+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_churn_dataset, task_id=load, execution_date=20250118T080813, start_date=20250118T080822, end_date=20250118T081132
[2025-01-18T08:11:32.533+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-18T08:11:32.551+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
