[2025-01-10T14:27:02.715+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prepare_churn_dataset.extract scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2025-01-10T14:27:02.722+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prepare_churn_dataset.extract scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2025-01-10T14:27:02.722+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-01-10T14:27:02.735+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2023-01-01 00:00:00+00:00
[2025-01-10T14:27:02.742+0000] {standard_task_runner.py:57} INFO - Started process 106 to run task
[2025-01-10T14:27:02.747+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'prepare_churn_dataset', 'extract', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/churn.py', '--cfg-path', '/tmp/tmpiiz1943k']
[2025-01-10T14:27:02.749+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask extract
[2025-01-10T14:27:02.832+0000] {task_command.py:416} INFO - Running <TaskInstance: prepare_churn_dataset.extract scheduled__2023-01-01T00:00:00+00:00 [running]> on host 6c2c8705fe78
[2025-01-10T14:27:02.960+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prepare_churn_dataset' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2025-01-10T14:27:02.965+0000] {base.py:73} INFO - Using connection ID 'source_db' for task execution.
[2025-01-10T14:27:03.130+0000] {warnings.py:109} WARNING - /opt/***/dags/churn.py:81: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(sql, conn)

[2025-01-10T14:27:03.528+0000] {python.py:194} INFO - Done. Returned value was:      customer_id  begin_date  ... dependents multiple_lines
0     7590-VHVEG  2020-01-01  ...         No           None
1     5575-GNVDE  2017-04-01  ...         No             No
2     3668-QPYBK  2019-10-01  ...         No             No
3     7795-CFOCW  2016-05-01  ...         No           None
4     9237-HQITU  2019-09-01  ...         No             No
...          ...         ...  ...        ...            ...
7038  6840-RESVB  2018-02-01  ...        Yes            Yes
7039  2234-XADUH  2014-02-01  ...        Yes            Yes
7040  4801-JZAZL  2019-03-01  ...        Yes           None
7041  8361-LTMKD  2019-07-01  ...         No            Yes
7042  3186-AJIEK  2014-08-01  ...         No             No

[7043 rows x 20 columns]
[2025-01-10T14:27:03.612+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py:373: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if _pandas_api.is_sparse(col):

[2025-01-10T14:27:03.709+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_churn_dataset, task_id=extract, execution_date=20230101T000000, start_date=20250110T142702, end_date=20250110T142703
[2025-01-10T14:27:03.769+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-01-10T14:27:03.795+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-30T06:10:58.162+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T06:10:58.179+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prepare_churn_dataset.extract scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2025-01-30T06:10:58.187+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prepare_churn_dataset.extract scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2025-01-30T06:10:58.187+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-30T06:10:58.198+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2023-01-01 00:00:00+00:00
[2025-01-30T06:10:58.205+0000] {standard_task_runner.py:72} INFO - Started process 103 to run task
[2025-01-30T06:10:58.217+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'prepare_churn_dataset', 'extract', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/churn.py', '--cfg-path', '/tmp/tmpz9uklhto']
[2025-01-30T06:10:58.219+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask extract
[2025-01-30T06:10:58.300+0000] {task_command.py:467} INFO - Running <TaskInstance: prepare_churn_dataset.extract scheduled__2023-01-01T00:00:00+00:00 [running]> on host 0be31ceb717f
[2025-01-30T06:10:58.392+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='prepare_churn_dataset' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2025-01-30T06:10:58.398+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-30T06:10:58.399+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-30T06:10:58.400+0000] {logging_mixin.py:190} INFO - Current task name:extract state:running start_date:2025-01-30 06:10:58.180099+00:00
[2025-01-30T06:10:58.401+0000] {logging_mixin.py:190} INFO - Dag name:prepare_churn_dataset and current dag run status:running
[2025-01-30T06:10:58.401+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T06:10:58.405+0000] {churn.py:71} INFO - Извлечение данных из источника.
[2025-01-30T06:10:58.423+0000] {base.py:84} INFO - Retrieving connection 'source_db'
[2025-01-30T06:10:58.424+0000] {sql.py:186} WARNING - This setter is for backward compatibility and should not be used.
Since the introduction of connection property, the providers listed below breaks due to assigning value to self.connection in their __init__ method.
* apache-***-providers-mysql<5.7.1
* apache-***-providers-elasticsearch<5.5.1
* apache-***-providers-postgres<5.13.0
[2025-01-30T06:10:58.556+0000] {warnings.py:109} WARNING - /opt/***/dags/churn.py:86: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(sql, conn)

[2025-01-30T06:10:59.471+0000] {churn.py:88} INFO - Данные успешно извлечены.
[2025-01-30T06:10:59.472+0000] {python.py:240} INFO - Done. Returned value was:      customer_id  begin_date  ... dependents multiple_lines
0     7590-VHVEG  2020-01-01  ...         No           None
1     5575-GNVDE  2017-04-01  ...         No             No
2     3668-QPYBK  2019-10-01  ...         No             No
3     7795-CFOCW  2016-05-01  ...         No           None
4     9237-HQITU  2019-09-01  ...         No             No
...          ...         ...  ...        ...            ...
7038  6840-RESVB  2018-02-01  ...        Yes            Yes
7039  2234-XADUH  2014-02-01  ...        Yes            Yes
7040  4801-JZAZL  2019-03-01  ...        Yes           None
7041  8361-LTMKD  2019-07-01  ...         No            Yes
7042  3186-AJIEK  2014-08-01  ...         No             No

[7043 rows x 20 columns]
[2025-01-30T06:10:59.668+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T06:10:59.668+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=prepare_churn_dataset, task_id=extract, run_id=scheduled__2023-01-01T00:00:00+00:00, execution_date=20230101T000000, start_date=20250130T061058, end_date=20250130T061059
[2025-01-30T06:10:59.677+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-30T06:10:59.677+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-30T06:10:59.678+0000] {logging_mixin.py:190} INFO - Dag name:prepare_churn_dataset queued_at:2025-01-30 06:10:56.404238+00:00
[2025-01-30T06:10:59.678+0000] {logging_mixin.py:190} INFO - Task hostname:0be31ceb717f operator:_PythonDecoratedOperator
[2025-01-30T06:10:59.708+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T06:10:59.731+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-30T06:10:59.733+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
